import './globals.css';
import type { Metadata } from 'next';
import { Kufam } from 'next/font/google';

// Setting for default font-family
const kufam = Kufam({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={kufam.className}>{children}</body>
        </html>
    );
}
